### ISSUE TITLE
web3.eth.getStorageAt does not read correct address length

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#114]
```
  2) Contract: MinGov
       should allow to upgrade bridge:

      AssertionError: expected '0x175c067eef5cd8cd0358a547f846c9c295e93a' to equal '0x00175c067eef5cd8cd0358a547f846c9c295e93a'
      + expected - actual

      -0x175c067eef5cd8cd0358a547f846c9c295e93a
      +0x00175c067eef5cd8cd0358a547f846c9c295e93a
      
      at _callee6$ (test/minGov.js:140:12)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/minGov.js:9:191)
      at test/minGov.js:9:361
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by johannbarbie** [comment]
open this in web3
